CREATE TABLE T_CLIENTE (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  cpfcnpj VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE T_CLIENTE_HAS_T_IMPORT_EMAIL (
  T_CLIENTE_id INTEGER UNSIGNED NOT NULL,
  T_IMPORT_EMAIL_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(T_CLIENTE_id, T_IMPORT_EMAIL_id),
  INDEX t_cliente_has_t_email_FKIndex1(T_CLIENTE_id),
  INDEX t_cliente_has_t_email_FKIndex2(T_IMPORT_EMAIL_id)
);

CREATE TABLE T_CLIENTE_HAS_T_IMPORT_FTP (
  T_CLIENTE_id INTEGER UNSIGNED NOT NULL,
  T_IMPORT_FTP_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(T_CLIENTE_id, T_IMPORT_FTP_id),
  INDEX t_cliente_has_t_ftp_FKIndex1(T_CLIENTE_id),
  INDEX t_cliente_has_t_ftp_FKIndex2(T_IMPORT_FTP_id)
);

CREATE TABLE T_CLIENTE_HAS_T_IMPORT_PASTA (
  T_CLIENTE_id INTEGER UNSIGNED NOT NULL,
  T_IMPORT_PASTA_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(T_CLIENTE_id, T_IMPORT_PASTA_id),
  INDEX t_cliente_has_t_pasta_FKIndex1(T_CLIENTE_id),
  INDEX t_cliente_has_t_pasta_FKIndex2(T_IMPORT_PASTA_id)
);

CREATE TABLE T_IMPORT_ARQUIVO (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  T_IMPORT_LAYOUT_id INTEGER UNSIGNED NOT NULL,
  identificador_linha INTEGER UNSIGNED NULL,
  PRIMARY KEY(id, T_IMPORT_LAYOUT_id),
  INDEX t_arquivo_FKIndex1(T_IMPORT_LAYOUT_id)
);

CREATE TABLE T_IMPORT_CAMPO_TABELA (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  T_IMPORT_ARQUIVO_id INTEGER UNSIGNED NOT NULL,
  T_IMPORT_ARQUIVO_T_IMPORT_LAYOUT_id INTEGER UNSIGNED NOT NULL,
  caractere VARCHAR(20) NULL,
  indexador INTEGER UNSIGNED NULL,
  posicao_inicial INTEGER UNSIGNED NULL,
  posicao_final INTEGER UNSIGNED NULL,
  nome_campo VARCHAR NULL,
  nome_campo_tabela VARCHAR NULL,
  nome_tabela VARCHAR NULL,
  json_depara VARCHAR NULL,
  PRIMARY KEY(id, T_IMPORT_ARQUIVO_id, T_IMPORT_ARQUIVO_T_IMPORT_LAYOUT_id),
  INDEX t_delimitacoes_FKIndex1(T_IMPORT_ARQUIVO_id, T_IMPORT_ARQUIVO_T_IMPORT_LAYOUT_id)
);

CREATE TABLE T_IMPORT_EMAIL (
  id INTEGER UNSIGNED NOT NULL,
  pop3 VARCHAR(255) NOT NULL,
  usuario VARCHAR(20) NOT NULL,
  senha VARCHAR(20) NOT NULL,
  porta VARCHAR(20) NOT NULL,
  tls_ssl VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE T_IMPORT_FTP (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  servidor VARCHAR(255) NOT NULL,
  usuario VARCHAR(20) NOT NULL,
  senha VARCHAR(20) NOT NULL,
  porta VARCHAR(20) NOT NULL,
  tls_ssl VARCHAR(45) NOT NULL,
  diretorio VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE T_IMPORT_LAYOUT (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(255) NOT NULL,
  padrao INTEGER UNSIGNED NOT NULL,
  linha INTEGER UNSIGNED NULL,
  posicao_inicial INTEGER UNSIGNED NULL,
  posicao_final INTEGER UNSIGNED NULL,
  delimitador VARCHAR NULL,
  indexador INTEGER UNSIGNED NULL,
  PRIMARY KEY(id)
);

CREATE TABLE T_IMPORT_LAYOUT_CLIENTE (
  T_IMPORT_LAYOUT_id INTEGER UNSIGNED NOT NULL,
  T_CLIENTE_id INTEGER UNSIGNED NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NULL,
  PRIMARY KEY(T_IMPORT_LAYOUT_id, T_CLIENTE_id),
  INDEX t_layout_cliente_FKIndex1(T_IMPORT_LAYOUT_id),
  INDEX t_layout_cliente_FKIndex2(T_CLIENTE_id)
);

CREATE TABLE T_IMPORT_PASTA (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  servidor VARCHAR(45) NOT NULL,
  usuario VARCHAR(20) NOT NULL,
  senha VARCHAR(20) NOT NULL,
  caminho VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE T_IMPORT_RECEBIMENTO (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  T_IMPORT_LAYOUT_CLIENTE_T_IMPORT_LAYOUT_id INTEGER UNSIGNED NOT NULL,
  T_IMPORT_LAYOUT_CLIENTE_T_CLIENTE_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id, T_IMPORT_LAYOUT_CLIENTE_T_IMPORT_LAYOUT_id, T_IMPORT_LAYOUT_CLIENTE_T_CLIENTE_id),
  INDEX t_recebimento_FKIndex1(T_IMPORT_LAYOUT_CLIENTE_T_IMPORT_LAYOUT_id, T_IMPORT_LAYOUT_CLIENTE_T_CLIENTE_id)
);

CREATE TABLE t_usuarios (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  login VARCHAR(20) NOT NULL,
  senha VARCHAR(20) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  perfil INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id)
);


